### ISSUE TITLE
Second client join always fails

### ISSUE THREAD

**Issue by sdeck51** [ooonush/FishyUnityTransport#11] opened 2023-04-23 17:00 UTC
Hi,

Just got into fishnet and am trying to use this package for development to test over the network with a friend.  I'm using the [FishyUnityTransport](https://github.com/ooonush/FishyUnityTransport) 0.2.0, Unity 2021.3.23f1 and I've hooked it up to FPSLand (Pro), Lobby and Worlds (Pro), and the https://github.com/RidefortGames/FishNet-ThirdPersonPrediction projects and in each of them I swap out tugboat for this and switch the transport over. I'm starting a server and multiple clients.

I start up the server using the editor. I start up the first client, which connects. I start up a second client, but it fails to connect, and I get an error in my editor(running as a server) `Error sending message: -2, 0`. This error runs repeatedly forever. If I try joining with a third, 4th etc clients they are able to join. Its just the second client that always fails, and it happens on each project I've tried to integrate FishUnityTransport with.

![Screenshot 2023-04-23 105926](https://user-images.githubusercontent.com/9275239/233853707-de6dfd90-e0e2-4771-83e0-e6e5a104cd9b.png)

I tried using the editor as the second client to see if it would produce any error logs for more information, but it doesn't, though the same issue of the second client failing to connect still occurs.

I'll also note if I'm using Tugboat, this issue does not occur.

Thanks

**Comment by sdeck51** [comment] 2023-04-23 17:35
Did a little digging around, error is happening in the CommonSocket.cs file

`
if (result != (int)StatusCode.Success)
{
    Debug.LogError($"Error sending message:{result}, {FishyUnityTransport.ParseClientIdToTransportId(clientId)}");
    return;
}
`

BeginSend is returning a -2 which is a NetworkVersionMismatch
`
var connection = m_ConnectionList[id.m_NetworkId];
if (connection.Version != id.m_NetworkVersion)
    return (int)Error.StatusCode.NetworkVersionMismatch;
`
This is pretty odd as the Unity definition of this is when the protocol version is different. I don't know why that would be the case here. https://docs.unity3d.com/ScriptReference/Networking.NetworkError.VersionMismatch.html

**Comment by ooonush** [comment] 2023-04-24 04:17
Hi, thanks for the bug report! I found the cause of the bug and will release a new version soon.

**Comment by ooonush** [comment] 2023-04-24 04:40
Fixed in version 0.2.1

**Closed by ooonush** 2023-04-24 04:40 UTC
